routes/web.php
<?php

include __DIR__.'\\partials\\ConsultaExternaRoute.php';
include __DIR__.'\\partials\\EmergenciaRoute.php';
include __DIR__.'\\partials\\HospitalizacionRoute.php';
include __DIR__.'\\partials\\ProgramacionGeneralRoute.php';
include __DIR__.'\\partials\\ArchivoClinicoRoute.php';
// include __DIR__.'\\partials\\FacturacionGeneralRoute.php';
include __DIR__.'\\partials\\CajaRoute.php';
include __DIR__.'\\partials\\FarmaciaRoute.php';
include __DIR__.'\\partials\\EstadisticaRoute.php';
// include __DIR__.'\\partials\\CentroQuirurgicoRoute.php';
// include __DIR__.'\\partials\\ServicioSocialRoute.php';
include __DIR__.'\\partials\\GeneralRoute.php';
include __DIR__.'\\partials\\SeguridadRoute.php';
include __DIR__.'\\partials\\FacturacionRoute.php';
include __DIR__.'\\partials\\FactConfigRoute.php';
include __DIR__.'\\partials\\LaboratorioRoute.php';
include __DIR__.'\\partials\\ImagenologiaRoute.php';
include __DIR__.'\\partials\\SisRoute.php';
include __DIR__.'\\partials\\HisRoute.php';
include __DIR__.'\\partials\\SeguimientoRoute.php';


Auth::routes();

Route::get('/test', 'TestController@index');


Route::get('/dev/genera-sigh-datos', 'DevController@generaSighDatos');
Route::get('/dev/genera-sigh-comun', 'DevController@generaSighComun');
Route::get('/dev/test', 'DevController@test');

Route::get('/dev', 'DevController@index');
Route::get('/dev/design/{fileName}', 'DevController@design');
Route::get('/dev/list/{fileName}', 'DevController@list');
Route::get('/dev/searh/{fileName}', 'DevController@searh');
Route::get('/dev/procedures', 'DevController@procedures');
Route::get('/dev/create-model', 'DevController@createModel');

Route::get('/dev/generate-controllers', 'DevController@generateControllers');


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/api', 'ApiController@index');

Route::get('/partials', 'PartialController@index');



Route::middleware('auth')->group(function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/profile', 'UsuarioController@profile');
});


// Route::middleware('auth')->group(function () {

//     Route::prefix('seguridad')->group( function () {

//         Route::name('seguridad.')->group( function () {

//             Route::resource('/roles', 'Seguridad\RolController');
//             Route::get('/roles/delete', 'Seguridad\RolController@delete');
            
//         });

//     });
    
// });

// Route::middleware('auth')->group(function () {

//     Route::prefix('fact-config')->group( function () {

//         Route::name('fact-config.')->group( function () {

//             Route::resource('/catalogo-servicios', 'CatalogoServicioController');

//             Route::resource('/catalogo-bienes-insumos', 'CatalogoBienInsumoController');

//             Route::resource('/resultados-laboratorio', 'ConfigResultadoLaboratorioController');
//         });
//     });
// });


Route::get('/controles', 'ControlesController@index');

Route::middleware('auth')->group(function () {

    Route::prefix('laboratorio/insumos')->group( function () {

        Route::name('lab.')->group( function () {

            Route::get('/', 'Lab\InsumoController@index')->name('insumos');

            Route::resource('/consumos', 'Lab\InsumoConsumoController');

            Route::resource('/asignaciones', 'Lab\InsumoAsignacionController');
            Route::get('/asignaciones/partial/responsables', 'Lab\InsumoAsignacionController@partialResponsables');
            Route::get('/asignaciones/partial/modal-consumos', 'Lab\InsumoAsignacionController@partialModalConsumos');
            Route::get('/asignaciones/partial/tbody-consumos', 'Lab\InsumoAsignacionController@partialTbodyConsumos');
            
        });

    });

});

Route::middleware('auth')->group(function () {

    Route::prefix('laboratorio/patologia-clinica')->group( function () {

        Route::name('lab.')->group( function () {

            Route::get('/', 'PatClinicaController@index')->name('patologia-clinica');

            Route::resource('/ordenes', 'Lab\OrdenController');
    
            Route::get('/ordenes/{idMovimiento}/detalle', 'Lab\OrdenController@detalle')
                ->name('ordenes.detalle');
        
            Route::get('/ordenes/{idOrden}/previa', 'Lab\OrdenController@previa')
                ->name('ordenes.previa');
        
            Route::get('/ordenes/{idOrden}/imprimir', 'Lab\OrdenController@imprimir')
                ->name('ordenes.imprimir');
        
            Route::get('/ordenes/{idMovimiento}/servicio/{idProducto}', 'Lab\OrdenController@resultados')
                ->name('ordenes.resultados');
        
            Route::post('/actualizaResultados', 'Lab\OrdenController@actualizaResultados')
                ->name('ordenes.resultados-update');

            
            //CRUD MODELS
    
            Route::get('/config-antibiograma', 'Lab\ConfigAntibiogramaController@index')->name('config-antibiograma.index');
            Route::resource('/germenes', 'Lab\GermenController');
            Route::get('/germenes/{id}/delete', 'Lab\GermenController@delete');
            Route::resource('/antibioticos', 'Lab\AntibioticoController');
            Route::get('/antibioticos/{id}/delete', 'Lab\AntibioticoController@delete');

            Route::resource('/items', 'Lab\ItemController');
            Route::get('items/{id}/delete', 'Lab\ItemController@delete');
        
            Route::resource('refs', 'Lab\ValorReferenciaController');
            Route::get('refs/{id}/delete', 'Lab\ValorReferenciaController@delete');
    
            Route::resource('/firmas', 'Lab\FirmaController');
            Route::get('/firmas/{id}/delete', 'Lab\FirmaController@delete');
    
            Route::get('/estadisticas', 'Lab\EstadisticaController@index')->name('estadisticas.index');
            Route::get('/estadisticas/print', 'Lab\EstadisticaController@print')->name('estadisticas.print');
    
            Route::resource('/periodos', 'Lab\PeriodoIndicadorController');
            Route::get('/periodos/{id}/delete', 'Lab\PeriodoIndicadorController@delete');
            Route::get('/periodos/{id}/sumary', 'Lab\PeriodoIndicadorController@sumary');
            Route::post('/periodos/update-periodo-dia', 'Lab\PeriodoIndicadorController@updatePeriodoDia');
        });
        
    });
    
});

resources/views/0_laboratorio/patologia-clinica/periodo-indicadores/index.blade.php
@extends('layouts.master')

@section('lab', 'active menu-open')
@section('lab.pat-clinica', 'active')

@section('breadcrumb')
<li><a href="#">Inicio</a></li>
<li><a href="#">Laboratorio</a></li>
<li><a href="{{ route('lab.patologia-clinica') }}">Patologia clinica</a></li>
<li class="active">Periodo de indicadores</li>
@endsection

@section('content')

{{ Form::hidden('periodos-path-ctrl', route('lab.periodos.index')) }}

@include('partials.my-modal')

<div class="row">
    <div class="col-sm-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-w fa-calendar"></i> Periodos de indicadores</h3>
                <div class="box-tools pull-right">
                    <a href="#" class="btn btn-primary btn-xs periodos-btn-create"> <i class="fa fa-plus"></i> Crear</a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row" >

                    <div class="col-sm-12" style="margin-bottom:10px;">
                        {{ Form::open(['route' => ['lab.periodos.index'], 'id'=>'periodos-form-filtro', 'class'=> 'form-inline pull-right']) }}
                            <div class="form-group">
                                {{ Form::text('filtro', null, ['class'=>'form-control input-sm periodos-input-filtro']) }}
                            </div>
                            <button type="submit" class="btn btn-sm btn-default periodos-btn-buscar"> <i class="fa fa-search"></i></button>
                            <a href="#" class="btn btn-sm btn-default periodos-btn-limpiar"> <i class="fa fa-refresh"></i></a>
                        {{ Form::close() }}
                    </div>

                    <div class="col-sm-12 periodos-tabla">
                    
                    </div>
                </div>
    
            </div>
        </div>
    </div>

</div>     
        
@endsection


@section('scripts')
    <script src="{{ url('/template/pages/lab.periodos.js') }}"></script>
@endsection

resources/views/0_laboratorio/patologia-clinica/periodo-indicadores/show.blade.php
@extends('layouts.master')

@section('lab', 'active menu-open')
@section('lab.pat-clinica', 'active')

@section('breadcrumb')
<li><a href="#">Inicio</a></li>
<li><a href="#">Laboratorio</a></li>
<li><a href="{{ route('lab.patologia-clinica') }}">Patologia clinica</a></li>
<li><a href="{{ route('lab.periodos.index') }}">Periodo de indicadores</a></li>
<li class="active">Indicadores</li>
@endsection

@section('content')

{{ Form::hidden('periodos-path-ctrl', route('lab.periodos.index')) }}

@include('partials.my-modal')

<style>
    .cell-td {
        /* padding-left: 0px; padding-right: 0px; position:relative; width:20px; */
        /* padding-left: 0px; padding-right: 0px;  width:20px; */
        padding: 0px; width:20px;
    }

    .col-td {
        
    }

    .cell-input {
        /* border:0; width:100%; top:0px; position:absolute; height:100%; text-align: center; */
        border:0; width:100%; top:0px;  height:27px; text-align: center;
        background:#C4C4C4;
    }

</style>

<div class="row">
    <div class="col-sm-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><i class="fa fa-w fa-calendar"></i> Periodo</h3>
                <div class="box-tools pull-right">
                    <span class="badge bg-yellow">{{ $periodo->periodoTxt() }}</span>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered table-condensed">
                            @php
                                $cols = [];
                                foreach ($data as $row) { $cols = $row->dias; break; };
                            @endphp
                            <tr style="font-weight:bold; text-align: center; " class="bg-light-blue color-palette">
                                <td rowspan="2" style="vertical-align:middle;">INDICADORES</td>
                                <td colspan="{{ count($cols) }}">DIA</td>
                            </tr>
                            <tr style="text-align: center;" class="bg-light-blue disabled color-palette">
                                @foreach ($cols as $col)
                                    <td style="padding-left: 0px; padding-right: 0px;">{{ sprintf("%02d",$col->Dia) }}</td> 
                                @endforeach
                            </tr>
                            @foreach ($data as $row)
                            <tr>
                                @php
                                    $indicadorNombre = $row->indicador_nombre;
                                    $maxlen = 67;
                                    if( strlen($indicadorNombre) > $maxlen){
                                        $indicadorNombre = substr( $row->indicador_nombre, 0, $maxlen ).' ...';
                                    }
                                    
                                @endphp
                                <td title="{{ $row->indicador_nombre }}">{{ $indicadorNombre }}</td>
                                @foreach ($row->dias as $dia)
                                
                                <td class="cell-td" style="padding: 0px;">
                                    <input type="hidden" class="IdPeriodoDia" value="{{ $dia->IdPeriodoDia }}">
                                    <input type="text" value="{{$dia->Valor}}" class="cell-input write" readonly>
                                </td> 
                                @endforeach
                            </tr>
                            @endforeach   
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>     
        
@endsection


@section('scripts')
    <script src="{{ url('/template/pages/lab.periodos.show.js') }}"></script>
@endsection

resources/views/0_laboratorio/patologia-clinica/periodo-indicadores/sumary.blade.php
@extends('layouts.master')

@section('lab', 'active menu-open')
@section('lab.pat-clinica', 'active')

@section('breadcrumb')
<li><a href="#">Inicio</a></li>
<li><a href="#">Laboratorio</a></li>
<li><a href="{{ route('lab.patologia-clinica') }}">Patologia clinica</a></li>
<li><a href="{{ route('lab.periodos.index') }}">Periodo de indicadores</a></li>
<li class="active">Resumen</li>
@endsection

@section('content')
    <section class="invoice">
        <div class="row invoice-content">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <thead>
                        <tr> <td colspan="5"><i class="fa fa-calendar"></i> INDICADOR DE CALIDAD</td></tr>
                        <tr> <td colspan="5"><b>Periodo: </b><?=$periodo->periodoTxt()?></td></tr>
                        <tr> <td colspan="5"><b>Area:</b> <?=$periodo->area->NombreGrupo?></td> </tr>
                        <tr> <td colspan="5"><b>Descripcion:</b> <?=$periodo->Descrip?></td> </tr>
                        <tr>
                            <th>GRUPO</th>
                            <th>INDICADOR</th>
                            <th>TOTAL</th>
                            <th>PROMEDIO</th>
                            <th>PORCENTAJE</th>
                        </tr>
                    </thead>
                    @foreach($grupos as $grupo)
                        @php $showGrupo = true; @endphp
                        @foreach($grupo->indicadores as $indicador)
                        <tr>
                            @if($showGrupo)
                            <td rowspan="{{ count($grupo->indicadores) }}" width="100">{{ $grupo->Nombre }}</td>
                            @endif
                            <td>{{ $indicador->NombreIndicador }}</td>
                            <td>{{ $indicador->Suma }}</td>
                            <td>{{ number_format($indicador->Promedio, 2, '.', '') }}</td>
                            <td>
                                @php
                                    if($indicador->Total> 0 ){
                                        $porcent = ($indicador->Suma/$indicador->Total)*100;
                                        echo number_format($porcent, 2, '.', '').'%';
                                    }else{
                                        echo '0';
                                    }
                                @endphp
                            </td>
                        </tr>
                        @php $showGrupo = false; @endphp
                        @endforeach
                        
                    @endforeach
                </table>
            </div>
        </div>

        
    </section>

    <!-- this row will not appear when printing -->
    <a href="#" style="position:fixed; bottom:10px; right:2px;  z-index:90; border-radius:50%;"
            class="no-print btn btn-lg btn-primary btn-print" title="Imprimir"> <i class="fa fa-print"></i></a>
   
@endsection

@section('scripts')

    <script>
        $(function(){
            $(".btn-print").click(function(e) {
                e.preventDefault();
                window.print();
                $(this).blur()
            });
        });
    </script>
    
    
@endsection