routes/web.php
<?php

include __DIR__.'\\partials\\ConsultaExternaRoute.php';
include __DIR__.'\\partials\\EmergenciaRoute.php';
include __DIR__.'\\partials\\HospitalizacionRoute.php';
include __DIR__.'\\partials\\ProgramacionGeneralRoute.php';
include __DIR__.'\\partials\\ArchivoClinicoRoute.php';
// include __DIR__.'\\partials\\FacturacionGeneralRoute.php';
include __DIR__.'\\partials\\CajaRoute.php';
include __DIR__.'\\partials\\FarmaciaRoute.php';
include __DIR__.'\\partials\\EstadisticaRoute.php';
// include __DIR__.'\\partials\\CentroQuirurgicoRoute.php';
// include __DIR__.'\\partials\\ServicioSocialRoute.php';
include __DIR__.'\\partials\\GeneralRoute.php';
include __DIR__.'\\partials\\SeguridadRoute.php';
include __DIR__.'\\partials\\FacturacionRoute.php';
include __DIR__.'\\partials\\FactConfigRoute.php';
include __DIR__.'\\partials\\LaboratorioRoute.php';
include __DIR__.'\\partials\\ImagenologiaRoute.php';
include __DIR__.'\\partials\\SisRoute.php';
include __DIR__.'\\partials\\HisRoute.php';
include __DIR__.'\\partials\\SeguimientoRoute.php';


Auth::routes();

Route::get('/test', 'TestController@index');


Route::get('/dev/genera-sigh-datos', 'DevController@generaSighDatos');
Route::get('/dev/genera-sigh-comun', 'DevController@generaSighComun');
Route::get('/dev/test', 'DevController@test');

Route::get('/dev', 'DevController@index');
Route::get('/dev/design/{fileName}', 'DevController@design');
Route::get('/dev/list/{fileName}', 'DevController@list');
Route::get('/dev/searh/{fileName}', 'DevController@searh');
Route::get('/dev/procedures', 'DevController@procedures');
Route::get('/dev/create-model', 'DevController@createModel');

Route::get('/dev/generate-controllers', 'DevController@generateControllers');


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/api', 'ApiController@index');

Route::get('/partials', 'PartialController@index');



Route::middleware('auth')->group(function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/profile', 'UsuarioController@profile');
});


// Route::middleware('auth')->group(function () {

//     Route::prefix('seguridad')->group( function () {

//         Route::name('seguridad.')->group( function () {

//             Route::resource('/roles', 'Seguridad\RolController');
//             Route::get('/roles/delete', 'Seguridad\RolController@delete');
            
//         });

//     });
    
// });

// Route::middleware('auth')->group(function () {

//     Route::prefix('fact-config')->group( function () {

//         Route::name('fact-config.')->group( function () {

//             Route::resource('/catalogo-servicios', 'CatalogoServicioController');

//             Route::resource('/catalogo-bienes-insumos', 'CatalogoBienInsumoController');

//             Route::resource('/resultados-laboratorio', 'ConfigResultadoLaboratorioController');
//         });
//     });
// });


Route::get('/controles', 'ControlesController@index');

Route::middleware('auth')->group(function () {

    Route::prefix('laboratorio/insumos')->group( function () {

        Route::name('lab.')->group( function () {

            Route::get('/', 'Lab\InsumoController@index')->name('insumos');

            Route::resource('/consumos', 'Lab\InsumoConsumoController');

            Route::resource('/asignaciones', 'Lab\InsumoAsignacionController');
            Route::get('/asignaciones/partial/responsables', 'Lab\InsumoAsignacionController@partialResponsables');
            Route::get('/asignaciones/partial/modal-consumos', 'Lab\InsumoAsignacionController@partialModalConsumos');
            Route::get('/asignaciones/partial/tbody-consumos', 'Lab\InsumoAsignacionController@partialTbodyConsumos');
            
        });

    });

});

Route::middleware('auth')->group(function () {

    Route::prefix('laboratorio/patologia-clinica')->group( function () {

        Route::name('lab.')->group( function () {

            Route::get('/', 'PatClinicaController@index')->name('patologia-clinica');

            Route::resource('/ordenes', 'Lab\OrdenController');
    
            Route::get('/ordenes/{idMovimiento}/detalle', 'Lab\OrdenController@detalle')
                ->name('ordenes.detalle');
        
            Route::get('/ordenes/{idOrden}/previa', 'Lab\OrdenController@previa')
                ->name('ordenes.previa');
        
            Route::get('/ordenes/{idOrden}/imprimir', 'Lab\OrdenController@imprimir')
                ->name('ordenes.imprimir');
        
            Route::get('/ordenes/{idMovimiento}/servicio/{idProducto}', 'Lab\OrdenController@resultados')
                ->name('ordenes.resultados');
        
            Route::post('/actualizaResultados', 'Lab\OrdenController@actualizaResultados')
                ->name('ordenes.resultados-update');

            
            //CRUD MODELS
    
            Route::get('/config-antibiograma', 'Lab\ConfigAntibiogramaController@index')->name('config-antibiograma.index');
            Route::resource('/germenes', 'Lab\GermenController');
            Route::get('/germenes/{id}/delete', 'Lab\GermenController@delete');
            Route::resource('/antibioticos', 'Lab\AntibioticoController');
            Route::get('/antibioticos/{id}/delete', 'Lab\AntibioticoController@delete');

            Route::resource('/items', 'Lab\ItemController');
            Route::get('items/{id}/delete', 'Lab\ItemController@delete');
        
            Route::resource('refs', 'Lab\ValorReferenciaController');
            Route::get('refs/{id}/delete', 'Lab\ValorReferenciaController@delete');
    
            Route::resource('/firmas', 'Lab\FirmaController');
            Route::get('/firmas/{id}/delete', 'Lab\FirmaController@delete');
    
            Route::get('/estadisticas', 'Lab\EstadisticaController@index')->name('estadisticas.index');
            Route::get('/estadisticas/print', 'Lab\EstadisticaController@print')->name('estadisticas.print');
    
            Route::resource('/periodos', 'Lab\PeriodoIndicadorController');
            Route::get('/periodos/{id}/delete', 'Lab\PeriodoIndicadorController@delete');
            Route::get('/periodos/{id}/sumary', 'Lab\PeriodoIndicadorController@sumary');
            Route::post('/periodos/update-periodo-dia', 'Lab\PeriodoIndicadorController@updatePeriodoDia');
        });
        
    });
    
});

app/Http/Controllers/Estadistica/ConstanciasController.php
<?php
namespace App\Http\Controllers\Estadistica;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class ConstanciasController extends Controller
{
	const PATH_VIEW = 'estadistica.constancias.';

	public function __construct()
	{
		
	}

	public function index(Request $request)
	{
		if($request->ajax()) {
			$items = DB::table('empleados')->select('idEmpleado as id', 'Nombres as name')->paginate(10); //test data
			return view(self::PATH_VIEW.'partials.item-list', compact('items'));
		}
		return view(self::PATH_VIEW.'index');
	}

	public function create()
	{
		if(request()->ajax()) {
			return view(self::PATH_VIEW.'partials.item-create');
		}
	}

	public function store(Request $request)
	{
		dd('Implementar logica para el metodo store');

		if(request()->ajax()) {
			$this->validate($request, [
				'field' => 'required',
			]);

			$success = false;

			//write your code...

			return ['success' => $success];
		}
	}

	public function show($id)
	{
		if(request()->ajax()) {
			//DataFake
			$item = DB::table('empleados')->where('idEmpleado', $id)
				->select('idEmpleado as id', 'Nombres as name')->first();

			return view(self::PATH_VIEW.'partials.item-show', compact('item'));
		}
	}

	public function edit($id)
	{
		if(request()->ajax()) {
			//DataFake
			$item = DB::table('empleados')->where('idEmpleado', $id)
				->select('idEmpleado as id', 'Nombres as name')->first();

			return view(self::PATH_VIEW.'partials.item-edit', compact('item'));
		}
	}

	public function update(Request $request, $id)
	{
		dd('Implementar logica para el metodo update');

		if(request()->ajax()) {
			$this->validate($request, [
				'field' => 'required',
			]);

			$success = false;

			//write your code...

			return ['success' => $success];
		}
	}

	public function delete($id)
	{
		if(request()->ajax()) {
			//DataFake
			$item = DB::table('empleados')->where('idEmpleado', $id)
				->select('idEmpleado as id', 'Nombres as name')->first();

			return view(self::PATH_VIEW.'partials.item-delete', compact('item'));
		}
	}

	public function destroy($id)
	{
		dd('Implementar logica para el metodo destroy');

		if(request()->ajax()) {
			
			// $this->validate($request, [
			// 	'field' => 'required',
			// ]);
			
			$success = false;

			//write your code...

			return ['success' => $success];
		}
	}


	public function apiService(Request $request)
	{
		switch($request->name)
		{
			case 'data-example':
				return $this->getDataExample( $request );
			default:
				return null;
		}
	}

	private function getDataExample( $request )
	{
		return 'data example...';
	}

}

app/Http/Controllers/Lab/EstadisticaController.php
<?php

namespace App\Http\Controllers\Lab;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class EstadisticaController extends Controller
{
    const PATH_VIEW = 'laboratorio.patologia-clinica.estadisticas.';

    public function index(Request $request)
    {
        $desde = date('Y-m-01');

        $hasta = date('Y-m-d');

        $tarifas = \DB::select("SELECT * FROM TiposFinanciamiento 
        WHERE SeIngresPrecios = 1 AND IdTipoFinanciamiento >0
        ORDER BY Descripcion DESC");

        $areas = \DB::select("SELECT * FROM labGrupos ORDER BY NombreGrupo");

        return view(self::PATH_VIEW.'index', compact('tarifas', 'areas', 'desde', 'hasta') );
    }

    public function print(Request $request)
    {
        $request->validate([
            'desde' => 'required|date',
            'hasta' => 'required|date',
            'tarifas_id' => 'required',
            'areas_id' => 'required',
        ], [
            'desde.required' => 'Ingrese fecha inicial',
            'hasta.required' => 'Indique fecha final',
            'tarifas_id.required' => 'Seleccione al menos una tarifa',
            'areas_id.required' => 'Seleccione al menos una area',
        ]);

        return view(self::PATH_VIEW.'print')->with([
            'desde' => $request->desde,
            'hasta' => $request->hasta,
            'tarifasId' => $request->tarifas_id,
            'areasId' => $request->areas_id,
        ]);
    }

    public function create()
    {

    }

    public function store(Request $request)
    {

    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {

    }

    public function update(Request $request, $id)
    {

    }

    public function delete($id)
    {

    }

    public function destroy($id)
    {
 
    }
}

resources/views/0_laboratorio/patologia-clinica/estadisticas/index.blade.php
@extends('layouts.master')

@section('lab', 'active menu-open')
@section('lab.pat-clinica', 'active')

@section('breadcrumb')
<li><a href="#">Inicio</a></li>
<li><a href="#">Laboratorio</a></li>
<li><a href="{{ route('lab.patologia-clinica') }}">Patologia clinica</a></li>
<li class="active">Estadistica puebas</li>
@endsection

@section('content')

@include('partials.validator-message')

<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <i class="fa fa-bar-chart"></i>
                <h3 class="box-title">Estadistica</h3>

                <div class="box-tools pull-right">
                    <a class="btn btn-sm btn-primary" href="javascript: $('#form-print').submit()">
                        <span class="fa fa-file-pdf-o" aria-hidden="true"></span> GENERAR
                    </a>
                </div>

            </div>
            <!-- /.box-header -->
            <div class="box-body">

                {{ Form::open(['route' => ['lab.estadisticas.print'], 'method'=>'GET', 'id'=>'form-print']) }}
                    <div class="row">

                        <div class="form-group col-sm-6">
                            {{ Form::label('desde') }}
                            {{ Form::date('desde', $desde, ['class'=>'form-control input-sm']) }}
                        </div>

                        <div class="form-group col-sm-6">
                            {{ Form::label('hasta') }}
                            {{ Form::date('hasta', $hasta, ['class'=>'form-control input-sm']) }}
                        </div>

                        <div class="form-group col-sm-6">
                            <label for="desde">Tarifas</label>
                            <div style="height: 300px; overflow-y: scroll;">
                                <table class="table table-striped">
                                    @foreach($tarifas as $tarifa)
                                    <tr><td>
                                        <div class="checkbox" style="margin:0px">
                                            <label><input type="checkbox" name="tarifas_id[]" value="{{ $tarifa->IdTipoFinanciamiento }}" >
                                                {{ $tarifa->Descripcion}}                               
                                            </label>
                                        </div>
                                    </td></tr>
                
                                    @endforeach
                                </table>
                            </div>
                        </div>

                        <div class="form-group col-sm-6">
                            <label for="desde">Areas</label>
                            <div style="height: 300px; overflow-y: scroll;">
                                <table class="table table-striped">
                                    @foreach($areas as $area)
                                    <tr><td>
                                        <div class="checkbox" style="margin:0px">
                                            <label><input type="checkbox" name="areas_id[]" value="{{ $area->idGrupo }}" >
                                                {{ $area->NombreGrupo }}                              
                                            </label>
                                        </div>
                                    </td></tr>
                
                                    @endforeach
                                </table>
                            </div>
                            
                        </div>

                    </div>
                {{ Form::close() }}
      
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
@endsection

resources/views/0_laboratorio/patologia-clinica/estadisticas/print.blade.php
@extends('layouts.master')

@section('lab', 'active menu-open')
@section('lab.pat-clinica', 'active')

@section('breadcrumb')
<li><a href="#">Inicio</a></li>
<li><a href="#">Laboratorio</a></li>
<li><a href="{{ route('lab.patologia-clinica') }}">Patologia clinica</a></li>
<li><a href="{{ route('lab.estadisticas.index') }}">Estadistica</a></li>
<li class="active">Reporte</li>
@endsection

@section('content')

    <section class="invoice" id="invoice">
        <style>
            body { 
                /* font-size: 11px;  */
            }
            tr {
                -webkit-print-color-adjust: exact; 
            }
    
            table {
                width: 100%;
                /* border: 1px solid black; */
            }
            table > tbody > tr > td {
                /* border: 1px solid black; */
            }
    
            .line-bottom { border-bottom: 1px solid #ddd; }
            .line-bottom2 { border-bottom: 1px solid #000; }
    
            .bg-danger{ color:red; }
            .bg-warning{ color:orange; }
            .bg-success{ color:green; }
    
        </style>

        @php
            CONST PATH_PARTIALS = 'laboratorio.patologia-clinica.estadisticas.partials-print.';
        @endphp
    
        <div class="row">
            <div class="col-xs-12">
                <table >
                    <thead>
                        @include(PATH_PARTIALS.'header')
                    </thead>
                    <tbody>
                        <tr> <td> @include(PATH_PARTIALS.'tarifas') </td> </tr>
                        <tr> <td> @include(PATH_PARTIALS.'resumen') </td> </tr>
                    </tbody>
                </table>
            </div>
        </div>
    
        <!-- this row will not appear when printing -->
        <a href="#" style="position:fixed; bottom:10px; right:2px;  z-index:90; border-radius:50%;"
            class="no-print btn btn-lg btn-primary btn-print" title="imprimir"> <i class="fa fa-print"></i></a>
    
    </section>
    
    <script>
        $(function(){
            $(".btn-print").click(function (e) {
                e.preventDefault();
                window.print();
                $(this).blur()
            });
        });
    </script>

@endsection